name: Deploy to AWS Fargate

on:
  push:
    branches:
      - main  # Run this on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install AWS CDK
        run: |
          npm install -g aws-cdk
        

      - name: Install Dependencies
        run: |
          cd cdk-align-web
          mvn clean install

      - name: Synthesize CDK Stack
        run: |
          cd cdk-align-web
          cdk synth

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker Image
        run: |
          ECR_REPO="align-web"
          IMAGE_TAG="latest"
          docker build --no-cache -t $ECR_REPO:$IMAGE_TAG .
          docker tag $ECR_REPO:$IMAGE_TAG ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-2.amazonaws.com/$ECR_REPO:$IMAGE_TAG
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-2.amazonaws.com/$ECR_REPO:$IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Update CDK Stack with new Docker Image / Infrastructure Updates
        run: |
          cd cdk-align-web
          cdk deploy --require-approval never -c imageTag=$IMAGE_TAG

      - name: Force ECS Fargate Deployment
        run: |
          aws ecs update-service --cluster AlignWebCluster --service AlignWebFargateService --force-new-deployment